apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      initContainers:
        - name: sysctl
          image: busybox
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
          securityContext:
            privileged: true
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:1.1.0
          env:
            - name: discovery.type
              value: single-node
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
            - name: cluster.routing.allocation.disk.watermark.low
              value: "97%"
            - name: cluster.routing.allocation.disk.watermark.high
              value: "98%"
            - name: cluster.routing.allocation.disk.watermark.flood_stage
              value: "99%"
          ports:
            - containerPort: 9200
              name: rest
            - containerPort: 9600
              name: perf
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: opensearch-data
          persistentVolumeClaim:
            claimName: opensearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  selector:
    app: opensearch
  ports:
    - name: rest
      port: 9200
      targetPort: 9200
    - name: perf
      port: 9600
      targetPort: 9600
