#!/usr/bin/env bash
set -euo pipefail

build_number="${CI_BUILD_NUMBER:-0.0.0}"
docker_registry="${BUILD_DOCKER_REGISTRY:-dev.local}"
docker_repository="organisation-registry"
build_dir="${BUILD_STAGINGDIRECTORY:-$(pwd)/dist}"

target="${1:-Default}"

set_solution_info() {
  local assembly_version="2.${build_number}"

  cat > SolutionInfo.cs <<EOF
// Auto-Generated by build.sh; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersion("${assembly_version}")]
[assembly: AssemblyFileVersion("${assembly_version}")]
[assembly: AssemblyInformationalVersion("${build_number}")]
[assembly: AssemblyProduct("Basisregisters Vlaanderen")]
[assembly: AssemblyCopyright("Copyright (c) Vlaamse overheid")]
[assembly: AssemblyCompany("Vlaamse overheid")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "${assembly_version}";
        internal const System.String AssemblyFileVersion = "${assembly_version}";
        internal const System.String AssemblyInformationalVersion = "${build_number}";
        internal const System.String AssemblyProduct = "Basisregisters Vlaanderen";
        internal const System.String AssemblyCopyright = "Copyright (c) Vlaamse overheid";
        internal const System.String AssemblyCompany = "Vlaamse overheid";
    }
}
EOF
}

restore_tools() {
  dotnet tool restore
}

build_solution() {
  set_solution_info
  dotnet restore
  dotnet build OrganisationRegistry.sln --no-restore
}

test_solution() {
  build_solution
  dotnet test OrganisationRegistry.sln --no-build --no-restore --logger trx
}

site_build() {
  npm run build

  local dist="${build_dir}/OrganisationRegistry.UI/linux"
  local source="src/OrganisationRegistry.UI"

  mkdir -p "${dist}/wwwroot"
  cp -R "${source}/wwwroot/." "${dist}/wwwroot/"
  cp "${source}/Dockerfile" "${dist}/Dockerfile"
  cp "${source}/default.conf" "${dist}/default.conf"
  cp "${source}/config.js" "${dist}/config.js"
  cp "${source}/init.sh" "${dist}/init.sh"
}

vue_build() {
  local dist="${build_dir}/OrganisationRegistry.UI/linux"
  local source="src/OrganisationRegistry.UI"
  local vue_source="src/OrganisationRegistry.Vue2"

  npm install --legacy-peer-deps --prefix "${vue_source}"
  npm run build --prefix "${vue_source}"

  mkdir -p "${dist}/wwwroot/vue"
  cp -R "${vue_source}/dist/." "${dist}/wwwroot/vue/"
}

containerize_path() {
  local path="$1"
  local image_name="$2"
  local tag="${docker_registry}/${docker_repository}/${image_name}:${build_number}"
  local latest="${docker_registry}/${docker_repository}/${image_name}:latest"

  docker build "${path}" \
    --no-cache \
    --tag "${tag}" \
    --build-arg "build_number=${build_number}"

  docker tag "${tag}" "${latest}"
}

containerize_project() {
  local project="$1"
  local image_name="$2"

  containerize_path "${build_dir}/${project}/linux" "${image_name}"
}

restore_tools

case "${target}" in
  Default|Build_Solution)
    build_solution
    ;;
  SetSolutionInfo)
    set_solution_info
    ;;
  Test_Solution)
    test_solution
    ;;
  Site_Build)
    site_build
    ;;
  Vue_Build)
    site_build
    vue_build
    ;;
  Containerize_Api)
    containerize_project "OrganisationRegistry.Api" "api"
    ;;
  Containerize_AgentschapZorgEnGezondheid)
    containerize_project "OrganisationRegistry.AgentschapZorgEnGezondheid.FtpDump" "batch-agentschapzorgengezondheidftpdump"
    ;;
  Containerize_VlaanderenBeNotifier)
    containerize_project "OrganisationRegistry.VlaanderenBeNotifier" "batch-vlaanderenbe"
    ;;
  Containerize_ElasticSearch)
    containerize_project "OrganisationRegistry.ElasticSearch.Projections" "projections-elasticsearch"
    ;;
  Containerize_Delegations)
    containerize_project "OrganisationRegistry.Projections.Delegations" "projections-delegations"
    ;;
  Containerize_Reporting)
    containerize_project "OrganisationRegistry.Projections.Reporting" "projections-reporting"
    ;;
  Containerize_KboMutations)
    containerize_project "OrganisationRegistry.KboMutations" "kbo-mutations"
    ;;
  Containerize_Rebuilder)
    containerize_project "OrganisationRegistry.Rebuilder" "rebuilder"
    ;;
  Containerize_Site)
    site_build
    vue_build
    containerize_path "${build_dir}/OrganisationRegistry.UI/linux" "ui"
    ;;
  Containerize_AcmIdm)
    containerize_path "src/IdentityServer" "acmidm"
    ;;
  *)
    echo "Unknown build target: ${target}" >&2
    exit 1
    ;;
esac
