FROM node:16.15.0-alpine AS builder

WORKDIR /app

COPY package*.json .npmrc ./
RUN npm install --legacy-peer-deps

COPY . .
RUN NODE_OPTIONS="--max-old-space-size=4096" npm run build:dev

FROM nginx:stable-alpine

COPY src/OrganisationRegistry.UI/default.conf /etc/nginx/conf.d/default.conf
COPY src/OrganisationRegistry.UI/init.sh ./init.sh
RUN chmod +x ./init.sh

COPY --from=builder /app/src/OrganisationRegistry.UI/wwwroot /usr/share/nginx/html

EXPOSE 9007

ENTRYPOINT ["./init.sh"]
