version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'E@syP@ssw0rd'
    ports:
      - "21433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
  es:
    image: opensearchproject/opensearch:1.1.0
    environment:
      discovery.type: 'single-node'
      DISABLE_SECURITY_PLUGIN: true
      cluster.routing.allocation.disk.watermark.low: 97%
      cluster.routing.allocation.disk.watermark.high: 98%
      cluster.routing.allocation.disk.watermark.flood_stage: 99%
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
  acm:
    build: src/IdentityServer/
    ports:
      - "5050:80"
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: http://localhost:8180
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "80:9007"
    environment:
      API_ENDPOINT: http://localhost:9002
      UI_ENDPOINT: http://organisatie.dev-vlaanderen.local
      API_VERSION: local
      AIV_URI: https://www.vlaanderen.be/informatie-vlaanderen
      OTEL_SERVER_URI: ""
      OTEL_DISTRIBUTED_TRACING_ORIGINS: ""
    extra_hosts:
      - "host.docker.internal:host-gateway"

  seed:
    build: seed/
    environment:
      API_BASE: http://host.docker.internal:9002
      JWT_SIGNING_KEY: keycloak-demo-local-dev-secret-key-32b
      JWT_ISSUER: organisatieregister
      JWT_AUDIENCE: organisatieregister
      DEVELOPER_VO_ID: 9c2f7372-7112-49dc-9771-f127b048b4c7
      MSSQL_HOST: mssql
      MSSQL_USER: sa
      MSSQL_PASSWORD: 'E@syP@ssw0rd'
      MSSQL_DB: OrganisationRegistry
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: "no"

  wiremock:
    image: wiremock/wiremock:2.32.0
    container_name: or_wiremock
    ports:
      - 8080:8080
    command:
      - -verbose
      - -global-response-templating

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver

volumes:
  mssql-data:
  opensearch-data:
