// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.0.0.0")]
[assembly: AssemblyInformationalVersion("")]
[assembly: AssemblyProduct("Basisregisters Vlaanderen")]
[assembly: AssemblyCopyright("Copyright (c) Vlaamse overheid")]
[assembly: AssemblyCompany("Vlaamse overheid")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string AssemblyVersion = "2.0.0.0";
        internal const string AssemblyFileVersion = "2.0.0.0";
        internal const string AssemblyInformationalVersion = "";
        internal const string AssemblyProduct = "Basisregisters Vlaanderen";
        internal const string AssemblyCopyright = "Copyright (c) Vlaamse overheid";
        internal const string AssemblyCompany = "Vlaamse overheid";
    }
}
