export * from './mandates.module';
export * from './mandates.component';
export * from './overview';
export * from './linkperson';
export * from './linkfunction';
export * from './linkorganisation';
export * from './updateperson';
export * from './updatefunction';
export * from './updateorganisation';
