apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: wegwijs-demo
data:
  # Keycloak
  KEYCLOAK_EXTERNAL_URL: "http://keycloak.localhost:9080"
  KEYCLOAK_INTERNAL_URL: "http://keycloak"
  KEYCLOAK_REALM: "wegwijs"
  KEYCLOAK_TOKEN_ENDPOINT: "http://keycloak/realms/wegwijs/protocol/openid-connect/token"
  KEYCLOAK_JWKS_URI: "http://keycloak/realms/wegwijs/protocol/openid-connect/certs"
  KEYCLOAK_INTROSPECTION_ENDPOINT: "http://keycloak/realms/wegwijs/protocol/openid-connect/token/introspect"
  KEYCLOAK_AUTHORITY: "http://keycloak.localhost:9080/realms/wegwijs"

  # API
  API_INTERNAL_BASE_URL: "http://api/v1"
  API_EXTERNAL_BASE_URL: "http://api.localhost:9080/v1"
  OPENSEARCH_INTERNAL_URL: "http://opensearch:9200"
  WIREMOCK_INTERNAL_URL: "http://wiremock:8080"

  # App URLs
  APP_URL: "http://app.localhost:9080"
  UI_URL: "http://ui.localhost:9080"
