apiVersion: v1
kind: Secret
metadata:
  name: demo-secrets
  namespace: wegwijs-demo
type: Opaque
stringData:
  mssql-sa-password: "E@syP@ssw0rd"
  keycloak-admin: "admin"
  keycloak-admin-password: "admin"
  jwt-signing-key: "keycloak-demo-local-dev-secret-key-32b"
  jwt-issuer: "organisatieregister"
  jwt-audience: "organisatieregister"
  developer-vo-id: "9c2f7372-7112-49dc-9771-f127b048b4c7"
  cjm-client-id: "cjmClient"
  cjm-client-secret: "secret"
  orafin-client-id: "orafinClient"
  orafin-client-secret: "secret"
  nuxt-bff-client-secret: "nuxt-bff-secret"
  nuxt-session-secret: "changeme-32chars-minimum-secret!"
