name: cache-paket
description: Cache Paket

runs:
  using: 'composite'
  steps:

  - name: Cache Paket
    uses: actions/cache@v3
    with:
      path: |
        .paket/
        paket-files/
        packages/
      key: ${{ runner.os }}-paket-${{ hashFiles('**/paket.lock') }}
