// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/allowed': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/allowed.post').default>>>>
    }
    '/api/forbidden': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/forbidden.post').default>>>>
    }
    '/api/login': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login.get').default>>>>
    }
    '/api/logout': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/logout.get').default>>>>
    }
    '/api/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/me.get').default>>>>
    }
    '/api/organisation': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/organisation.get').default>>>>
    }
    '/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/callback.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}