#!/bin/sh

# Overwrite config.js with runtime values (use > for first line, >> for rest)
cat > /usr/share/nginx/html/config.js << EOF
// Runtime configuration generated by init.sh
window.organisationRegistryVersion="v2-${API_VERSION}";
window.organisationRegistryApiEndpoint="${API_ENDPOINT}";
window.organisationRegistryUiEndpoint="${UI_ENDPOINT}";
window.organisationRegistryInformatieVlaanderenLink="${AIV_URI}";
window.otelServerUri="${OTEL_SERVER_URI}";
window.otelDistributedTracingOrigins="${OTEL_DISTRIBUTED_TRACING_ORIGINS}";
EOF

nginx -g 'daemon off;'
