name: setup-dotnet
description: Setup .NET Core

inputs:
  version:
    description: 'Required dotnet version'
    required: true

runs:
  using: 'composite'
  steps:

  - name: Cache Paket
    uses: actions/cache@v3
    with:
      path: |
        .paket/
        paket-files/
        packages/
      key: ${{ runner.os }}-paket-${{ hashFiles('**/paket.lock') }}

  - name: Setup .NET Core
    uses: actions/setup-dotnet@v3
    with:
      dotnet-version: ${{ inputs.version }}

  - name: .NET version
    shell: bash
    run: dotnet --info

  - name: Restore dotnet tools
    shell: bash
    run: dotnet tool restore

  - name: Paket restore
    shell: bash
    run: dotnet paket restore
