name: Deploy to Environment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target environment (e.g. stg, tst, prd)'
        required: true
        type: string
      version:
        description: 'Version to deploy'
        required: true
        type: string

jobs:
  deploy_services:
    name: Deploy services to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services:
          [
            'organisation-api',
            'organisation-elasticsearch',
            'organisation-rebuilder',
            'organisation-ui',
          ]
    steps:
      - name: CD
        id: awscurl-polling-action
        env:
          BUILD_URL: ${{ vars.VBR_AWS_BUILD_API_DEVOPS }}/${{ matrix.services }}
          STATUS_URL: ${{ vars.VBR_AWS_BUILD_STATUS_API_DEVOPS }}/${{ matrix.services }}
        uses: informatievlaanderen/awscurl-polling-action/polling-action@main
        with:
          environment: ${{ inputs.environment }}
          version: ${{ inputs.version }}
          status-url: $STATUS_URL
          deploy-url: $BUILD_URL
          access-key: ${{ secrets.VBR_AWS_ACCESS_KEY_ID_DEVOPS }}
          secret-key: ${{ secrets.VBR_AWS_SECRET_ACCESS_KEY_DEVOPS }}
          interval: 2
          deploy-target: 'agb_ecs_service'
          domain: 'basisregisters'
          project: 'basisregisters'

      - name: output
        shell: bash
        run: |
          echo build-uuid: ${{ steps.awscurl-polling-action.outputs.build-uuid }}
          echo Status: ${{ steps.awscurl-polling-action.outputs.status }}
          echo ${{ steps.awscurl-polling-action.outputs.final-message }}

  deploy_scheduledtasks:
    name: Deploy scheduled tasks to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services:
          [
            'organisation-delegations',
            'organisation-kbomutations',
            'organisation-reporting',
            'organisation-vlaanderenbe',
            'organisation-zorgengezondheid',
          ]
    steps:
      - name: CD
        id: awscurl-polling-action
        env:
          BUILD_URL: ${{ vars.VBR_AWS_BUILD_API_DEVOPS }}/${{ matrix.services }}
          STATUS_URL: ${{ vars.VBR_AWS_BUILD_STATUS_API_DEVOPS }}/${{ matrix.services }}
        uses: informatievlaanderen/awscurl-polling-action/polling-action@main
        with:
          environment: ${{ inputs.environment }}
          version: ${{ inputs.version }}
          status-url: $STATUS_URL
          deploy-url: $BUILD_URL
          access-key: ${{ secrets.VBR_AWS_ACCESS_KEY_ID_DEVOPS }}
          secret-key: ${{ secrets.VBR_AWS_SECRET_ACCESS_KEY_DEVOPS }}
          interval: 2
          deploy-target: 'ecs_scheduled_task'
          domain: 'basisregisters'
          project: 'basisregisters'

      - name: output
        shell: bash
        run: |
          echo build-uuid: ${{ steps.awscurl-polling-action.outputs.build-uuid }}
          echo Status: ${{ steps.awscurl-polling-action.outputs.status }}
          echo ${{ steps.awscurl-polling-action.outputs.final-message }}
