name: Manual Production NEW

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (format: x.xxx.x, ie: 1.221.1)'
        required: true

jobs:
  deployment:
    if: github.repository_owner == 'Informatievlaanderen'
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: prd
      version: ${{ github.event.inputs.version }}
    secrets: inherit
