name: Manual Staging NEW

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  deployment:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: stg
      version: ${{ github.event.inputs.version }}
    secrets: inherit
