name: CD Staging

on:
  release:
    types: [published]

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services:
          [
            'organisation-registry-api',
            'organisation-registry-delegations',
            'organisation-registry-elasticsearch',
            'organisation-registry-kbomutations',
            'organisation-registry-reporting',
            'organisation-registry-scheduler',
            'organisation-registry-ui',
            'organisation-registry-vlaanderenbe',
            'applications/organisation-registry-zorgengezondheid',
          ]
    steps:
      - uses: actions/github-script@v4
        id: get-version
        with:
          script: echo $GITHUB_REF | sed 's/v//'
          result-encoding: string
      - name: CD
        env:
          BUILD_URL: ${{ secrets.VBR_AWS_BUILD_API }}/${{matrix.services}}
          STATUS_URL: ${{ secrets.VBR_AWS_BUILD_STATUS_API }}/${{matrix.services}}
        uses: informatievlaanderen/awscurl-polling-action@main
        with:
          environment: stg
          version: ${{ steps.get-version.outputs.result }}
          status-url: $STATUS_URL
          deploy-url: $BUILD_URL
          access-key: ${{ secrets.VBR_AWS_BUILD_USER_ACCESS_KEY_ID }}
          secret-key: ${{ secrets.VBR_AWS_BUILD_USER_SECRET_ACCESS_KEY }}
          region: eu-west-1
          interval: 2
      - name: output
        shell: bash
        run: |
          echo build-uuid: ${{ steps.awscurl-polling-action.outputs.build-uuid }}
          echo Status: ${{ steps.awscurl-polling-action.outputs.status }}
          echo ${{ steps.awscurl-polling-action.outputs.final-message }}
